sylius_mailer:
    sender:
        name: SyliusOnlineCourse admin
        address: sylius@example.com
    emails:
        app_supplier_trusted:
            subject: "You've has been trusted!"
            template: "Supplier/Email/supplierTrusted.html.twig"
